name: Java CI

on: 
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 初始化环境
      uses: actions/checkout@v1
    - name: 使用JDK1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: 构建
      run: |
        chmod +x ./gradlew
        ./gradlew build
    - name: 发布
      uses: actions/upload-artifact@master
      with: 
        name: BaiMusic-Sponge
        path: build/libs
